---
# Configuration For PlayerInfo Plugin By Matthww
# True = Enabled
# False = Disabled

#Save playerdata
Save: false

# Show players name
Name: false

# Show players IP
IP: false

# Show players ping
Ping: false

# Show players Device OS
# (Android, iOS etc.)
OS: false

# Show players Device Model
# (iPhone 7 etc.)
Model: false

# Show players UI settings
# (Classic UI or Pocket UI)
UI: false

# Show players GUI scale settings
GUI: false

# Show players controls
# (Touch, Mouse or Controller)
Controls: false

# Show players health
Health: false

# Show players position
Position: false
...
